### ISSUE TITLE
Mesa support full OpenGL contexts via EGL selection, support in Android-x86 also?

### ISSUE THREAD

**Issue by oscarbg** [maurossi/mesa#1]
Posted here:
https://groups.google.com/forum/#!topic/android-x86/UViuriuwh68
I asked Chih-Wei Huang:

since Mesa supports full OpenGL contexts in addition to OpenGL ES contexts created via EGL API selection can you support also full OpenGL contexts on Android similar to NVidia Shield Tablet supports.. 
i.e. support OpenGL in EGL_RENDERABLE_TYPE
see for example Shield Tablet gfxbench report:
https://gfxbench.com/resultdetails.jsp?resultid=hSmWKjDNbkDzGAPsqQ5d8Q
It says:
EGL_RENDERABLE_TYPE: OpenGL_ES
OpenGL_ES_2
OpenGL
(77) 

He answered: "I have no idea about that topic. "

Perhaps currently Android-x86 5.1.1 supports but in case not, you seem the correct guy to ask
to patch Mesa Android support for enabling full OpenGL contexts in Android..
also related to full OpenGL context support, eventually LLVM version will be important for radeonsi support.. for example supporing tesselation shaders and perhaps fp64 support extensions require new LLVM 3.7.0.. with it we get GL4.1 support with LLVM 3.6.x we get only OpenGL 3.3 support..

so if not difficult can you be fast upgrading LLVM version for Mesa Android if/once full OpenGL context support lands..

what are your thoughts?

**Comment by maurossi** [comment]
Hi Oscar,

I'm not confident it's a quick task

I tried some time ago to build more recent LLVM, using AOSP's latest LLVM
project in marshmallow branch, but there is a lot of building errors
related to AMDGPU code and the new MCJIT library for JIT compiling.

Using the latest 3.7.0 posed even more problems in building, but at this
point OpenGL 2.0 or 3.0 at top is exposed to SurfaceFlinger and there are
still two major bugs one in nouveau (gpu lockup) and the other in radeonsi
(GUI restarts with common OpenGL demo apps)

When AMDGPU support will be evaluated, we will need to move to more recent
LLVM, but it's just a concept now.

Regarding EGL_RENDERABLE_TYPE, I need to have a google search session to
see what it does, I think it is mesa to espose OpenGL capabilities, but
have you already performed an assessment about impact in mesa itself to
espose that EGL estension or it is already there?

Mauro

Il giovedì 8 ottobre 2015, Oscar Barenys <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> ha scritto:

**Comment by maurossi** [comment]
Closing,

as AOSP/android-x86 build system uses specific llvm versions
but it is possible to build a "side" lllvm project, e.g. external/llvm50 tweaked to have libraries and Android.mk makefile variables different from mainstream external/llvm like in [1]
and modify mesa's Android.mk in order to accomodate new libLLVM50 shared dependency
and definitions of HAVE_LLVM

```
   $(if $(filter 7,$(MESA_ANDROID_MAJOR_VERSION)), \
-    $(eval LOCAL_CFLAGS += -DHAVE_LLVM=0x0308 -DMESA_LLVM_VERSION_PATCH=0)) \
+    $(eval LOCAL_CFLAGS += -DHAVE_LLVM=0x0500 -DMESA_LLVM_VERSION_PATCH=0)) \
   $(if $(filter 8,$(MESA_ANDROID_MAJOR_VERSION)), \
-    $(eval LOCAL_CFLAGS += -DHAVE_LLVM=0x0309 -DMESA_LLVM_VERSION_PATCH=0)) \
+    $(eval LOCAL_CFLAGS += -DHAVE_LLVM=0x0500 -DMESA_LLVM_VERSION_PATCH=0)) \
```

The only constraint is to use a mesa version that supports the chosen llvm version.

[1] https://github.com/yuq/llvm/commits/llvm50-rc2
